### ISSUE TITLE
Move source key from .YAML to CLI argument.

### ISSUE THREAD

**Issue by siraphobk** [siraphobk/go-gen-interface#14]
**Is your feature request related to a problem? Please describe.**
```yaml
include_unexported_methods: false
include_unexported_structs: false
output:
  pre_import_packages:
    - "github.com/google/uuid"
  package_name: database
  interface_prefix:
  interface_suffix: Database
source:                                    <---- This key
- './../database/dbsql/*.go'
ignored_structs:
```
Move `This key` to CLI argument. Maybe using a flag as a string input.
